version: '3'

services:
  mongodb:
    image: 'mongo:4.0'
    restart: always
    volumes:
      - db-data:/data/db
    networks:
      - app_net

  web:
    image: nginx:1.15-alpine
    volumes:
      - socket-data:/var/run


  rails:
    depends_on:
      - mongodb
      - web
    build: .
    ports:
      - 3000:3000
    networks:
      - app_net
    volumes:
      - socket-data:/var/run
volumes:
  db-data:
  socket-data:
networks:
  app_net:
