version: '3'

services:
  mongodb:
    image: 'mongo:4.0'
    volumes:
      - db-data:/data/db
    networks:
      - app_net

  rails:
    depends_on:
      - mongodb
    build: .
    ports:
      - 3000:3000
    networks:
      - app_net

volumes:
  db-data:
networks:
  app_net:
