version: '3'

services:
  mongodb:
    image: 'mongo:4.0'
    restart: always
    volumes:
      - db-data:/data/db
    networks:
      - app_net

  rails:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    networks:
      - app_net
    volumes:
      - www-data:/var/run

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - www-data:/var/run
    ports:
      - 80:80
    depends_on:
      - rails

volumes:
  db-data:
  www-data:
networks:
  app_net:
