version: '3'

services:
  mongodb:
    image: 'mongo:4.0'
    volumes:
      - 'mongodb:/etc/mongo'
    networks:
      - app_net

  website:
    depends_on:
      - 'mongodb'
    build: .
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    networks:
      - app_net

volumes:
  mongodb:

networks:
  app_net:
    driver: bridge
